<#
.SYNOPSIS
    Creates a new Microsoft Fabric Data Agent item via the Fabric REST API.

.DESCRIPTION
    Authenticates to Azure, creates a Fabric Data Agent item in the specified workspace,
    and optionally applies an Operations Agent definition (Configurations.json).

.PARAMETER WorkspaceId
    The GUID of the Fabric workspace where the data agent will be created.

.PARAMETER AgentName
    Display name for the new data agent.

.PARAMETER Description
    Optional description for the data agent.

.PARAMETER DefinitionPath
    Optional path to a Configurations.json file to apply as the item definition.

.EXAMPLE
    .\New-FabricDataAgent.ps1 -WorkspaceId "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" -AgentName "Sales Data Agent"

.EXAMPLE
    .\New-FabricDataAgent.ps1 -WorkspaceId "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" -AgentName "Ops Monitor" -DefinitionPath "./Configurations.json"

.NOTES
    Requires: PowerShell 7.4+, Az.Accounts module
    Author:   Generated by Fabric Data Agents Skill
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')]
    [string]$WorkspaceId,

    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$AgentName,

    [Parameter()]
    [string]$Description = '',

    [Parameter()]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$DefinitionPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#region Authentication
Write-Host '[1/4] Authenticating to Azure...' -ForegroundColor Cyan
try {
    $context = Get-AzContext
    if (-not $context) {
        Connect-AzAccount | Out-Null
    }
    $tokenResponse = Get-AzAccessToken -ResourceUrl 'https://api.fabric.microsoft.com'
    $token = $tokenResponse.Token
}
catch {
    Write-Error "Authentication failed: $_"
    exit 1
}
Write-Host '      Authentication successful.' -ForegroundColor Green
#endregion

#region Configuration
$baseUri = 'https://api.fabric.microsoft.com/v1'
$headers = @{
    'Authorization' = "Bearer $token"
    'Content-Type'  = 'application/json'
}
#endregion

#region Create Item
Write-Host '[2/4] Creating Fabric Data Agent item...' -ForegroundColor Cyan

$createBody = @{
    displayName = $AgentName
    type        = 'DataAgent'
} | ConvertTo-Json -Depth 10

if ($Description) {
    $createObj = $createBody | ConvertFrom-Json
    $createObj | Add-Member -NotePropertyName 'description' -NotePropertyValue $Description
    $createBody = $createObj | ConvertTo-Json -Depth 10
}

try {
    $createResponse = Invoke-RestMethod `
        -Uri "$baseUri/workspaces/$WorkspaceId/items" `
        -Method Post `
        -Headers $headers `
        -Body $createBody

    $itemId = $createResponse.id
    Write-Host "      Data Agent created. Item ID: $itemId" -ForegroundColor Green
}
catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    $errorBody = $_.ErrorDetails.Message
    Write-Error "Failed to create Data Agent (HTTP $statusCode): $errorBody"
    exit 1
}
#endregion

#region Apply Definition (Optional)
if ($DefinitionPath) {
    Write-Host '[3/4] Applying Operations Agent definition...' -ForegroundColor Cyan

    $definitionJson = Get-Content -Path $DefinitionPath -Raw -Encoding UTF8
    $definitionBase64 = [Convert]::ToBase64String(
        [System.Text.Encoding]::UTF8.GetBytes($definitionJson)
    )

    $definitionBody = @{
        definition = @{
            parts = @(
                @{
                    path        = 'Configurations.json'
                    payload     = $definitionBase64
                    payloadType = 'InlineBase64'
                }
            )
        }
    } | ConvertTo-Json -Depth 10

    try {
        Invoke-RestMethod `
            -Uri "$baseUri/workspaces/$WorkspaceId/items/$itemId/updateDefinition" `
            -Method Post `
            -Headers $headers `
            -Body $definitionBody | Out-Null

        Write-Host '      Definition applied successfully.' -ForegroundColor Green
    }
    catch {
        $statusCode = $_.Exception.Response.StatusCode.value__
        $errorBody = $_.ErrorDetails.Message
        Write-Warning "Failed to apply definition (HTTP $statusCode): $errorBody"
        Write-Warning 'The item was created but the definition was not applied.'
    }
}
else {
    Write-Host '[3/4] No definition file provided, skipping.' -ForegroundColor Yellow
}
#endregion

#region Output Summary
Write-Host '[4/4] Summary' -ForegroundColor Cyan
Write-Host "      Workspace ID : $WorkspaceId"
Write-Host "      Item ID      : $itemId"
Write-Host "      Display Name : $AgentName"
Write-Host "      Portal URL   : https://app.fabric.microsoft.com/groups/$WorkspaceId/items/$itemId"
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  1. Open the agent in the Fabric portal to add data sources'
Write-Host '  2. Configure agent instructions and example queries'
Write-Host '  3. Test with representative questions'
Write-Host '  4. Publish when ready to share'
#endregion
