<#
.SYNOPSIS
    Validates Microsoft Fabric Data Agent prerequisites and configuration.

.DESCRIPTION
    Diagnostic script that checks tenant settings, workspace capacity, data source
    accessibility, and common configuration issues for Fabric Data Agent deployments.
    Outputs a structured report identifying pass/fail/warning status for each check.

.PARAMETER WorkspaceId
    The GUID of the Fabric workspace containing (or intended to contain) the data agent.

.PARAMETER TenantId
    Optional. The Azure AD tenant ID. If not specified, uses the current context.

.PARAMETER IncludeCapacityCheck
    Switch to include capacity SKU and region validation (requires admin permissions).

.PARAMETER OutputFormat
    Output format: 'Console' (default), 'Json', or 'Markdown'.

.EXAMPLE
    ./Test-FabricDataAgentConfig.ps1 -WorkspaceId "12345678-abcd-1234-abcd-123456789012"

.EXAMPLE
    ./Test-FabricDataAgentConfig.ps1 -WorkspaceId "12345678-abcd-1234-abcd-123456789012" -OutputFormat Markdown -Verbose

.NOTES
    Requires: PowerShell 7+, Az.Accounts module
    Author: Generated by AI Skill
    Version: 1.0.0
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, HelpMessage = "Fabric workspace GUID")]
    [ValidatePattern('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')]
    [string]$WorkspaceId,

    [Parameter(Mandatory = $false)]
    [string]$TenantId,

    [Parameter(Mandatory = $false)]
    [switch]$IncludeCapacityCheck,

    [Parameter(Mandatory = $false)]
    [ValidateSet('Console', 'Json', 'Markdown')]
    [string]$OutputFormat = 'Console'
)

#region Helper Functions

function New-CheckResult {
    param(
        [string]$Category,
        [string]$Check,
        [ValidateSet('Pass', 'Fail', 'Warning', 'Info', 'Skipped')]
        [string]$Status,
        [string]$Message,
        [string]$Remediation = ''
    )
    [PSCustomObject]@{
        Category    = $Category
        Check       = $Check
        Status      = $Status
        Message     = $Message
        Remediation = $Remediation
        Timestamp   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    }
}

function Write-CheckResult {
    param([PSCustomObject]$Result)

    $icon = switch ($Result.Status) {
        'Pass'    { '[PASS]' }
        'Fail'    { '[FAIL]' }
        'Warning' { '[WARN]' }
        'Info'    { '[INFO]' }
        'Skipped' { '[SKIP]' }
    }

    $color = switch ($Result.Status) {
        'Pass'    { 'Green' }
        'Fail'    { 'Red' }
        'Warning' { 'Yellow' }
        'Info'    { 'Cyan' }
        'Skipped' { 'DarkGray' }
    }

    Write-Host "$icon " -ForegroundColor $color -NoNewline
    Write-Host "$($Result.Category) > $($Result.Check): " -NoNewline
    Write-Host $Result.Message -ForegroundColor $color

    if ($Result.Remediation -and $Result.Status -in @('Fail', 'Warning')) {
        Write-Host "       Remediation: $($Result.Remediation)" -ForegroundColor DarkYellow
    }
}

function Get-FabricAccessToken {
    try {
        $context = Get-AzContext -ErrorAction Stop
        if (-not $context) {
            throw "No Azure context found."
        }
        $token = Get-AzAccessToken -ResourceUrl 'https://api.fabric.microsoft.com' -ErrorAction Stop
        return $token.Token
    }
    catch {
        Write-Verbose "Failed to get Fabric access token: $_"
        return $null
    }
}

#endregion

#region Main Execution

$results = [System.Collections.Generic.List[PSCustomObject]]::new()

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Fabric Data Agent Diagnostic Report" -ForegroundColor Cyan
Write-Host " $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# ---- Check 1: PowerShell Version ----
$psVersion = $PSVersionTable.PSVersion
if ($psVersion.Major -ge 7) {
    $results.Add((New-CheckResult -Category 'Environment' -Check 'PowerShell Version' `
        -Status 'Pass' -Message "PowerShell $psVersion detected"))
}
else {
    $results.Add((New-CheckResult -Category 'Environment' -Check 'PowerShell Version' `
        -Status 'Warning' -Message "PowerShell $psVersion detected. 7+ recommended." `
        -Remediation 'Install PowerShell 7+: https://learn.microsoft.com/powershell/scripting/install/installing-powershell'))
}

# ---- Check 2: Az Module ----
$azModule = Get-Module -Name Az.Accounts -ListAvailable -ErrorAction SilentlyContinue
if ($azModule) {
    $results.Add((New-CheckResult -Category 'Environment' -Check 'Az.Accounts Module' `
        -Status 'Pass' -Message "Az.Accounts $($azModule[0].Version) installed"))
}
else {
    $results.Add((New-CheckResult -Category 'Environment' -Check 'Az.Accounts Module' `
        -Status 'Fail' -Message 'Az.Accounts module not found' `
        -Remediation 'Install-Module Az.Accounts -Scope CurrentUser'))
}

# ---- Check 3: Azure Context ----
try {
    $context = Get-AzContext -ErrorAction Stop
    if ($context) {
        $results.Add((New-CheckResult -Category 'Authentication' -Check 'Azure Context' `
            -Status 'Pass' -Message "Signed in as $($context.Account.Id) in tenant $($context.Tenant.Id)"))
    }
    else {
        $results.Add((New-CheckResult -Category 'Authentication' -Check 'Azure Context' `
            -Status 'Fail' -Message 'No active Azure context' `
            -Remediation 'Run: Connect-AzAccount'))
    }
}
catch {
    $results.Add((New-CheckResult -Category 'Authentication' -Check 'Azure Context' `
        -Status 'Fail' -Message "Azure context check failed: $_" `
        -Remediation 'Run: Connect-AzAccount'))
}

# ---- Check 4: Fabric API Token ----
$token = Get-FabricAccessToken
if ($token) {
    $results.Add((New-CheckResult -Category 'Authentication' -Check 'Fabric API Token' `
        -Status 'Pass' -Message 'Successfully acquired Fabric API access token'))
}
else {
    $results.Add((New-CheckResult -Category 'Authentication' -Check 'Fabric API Token' `
        -Status 'Fail' -Message 'Cannot acquire Fabric API token' `
        -Remediation 'Ensure Az context has Fabric permissions. Run: Connect-AzAccount'))
}

# ---- Check 5: Workspace Access ----
if ($token) {
    try {
        $headers = @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' }
        $uri = "https://api.fabric.microsoft.com/v1/workspaces/$WorkspaceId"
        $workspace = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get -ErrorAction Stop

        $results.Add((New-CheckResult -Category 'Workspace' -Check 'Workspace Access' `
            -Status 'Pass' -Message "Workspace '$($workspace.displayName)' accessible"))

        Write-Verbose "Workspace: $($workspace.displayName) | ID: $($workspace.id)"
    }
    catch {
        $statusCode = $_.Exception.Response.StatusCode.value__
        $msg = switch ($statusCode) {
            403 { 'Access denied. User lacks workspace permissions.' }
            404 { 'Workspace not found. Verify the WorkspaceId GUID.' }
            default { "API error (HTTP $statusCode): $_" }
        }
        $results.Add((New-CheckResult -Category 'Workspace' -Check 'Workspace Access' `
            -Status 'Fail' -Message $msg `
            -Remediation 'Verify WorkspaceId and ensure user has Contributor or higher role'))
    }
}
else {
    $results.Add((New-CheckResult -Category 'Workspace' -Check 'Workspace Access' `
        -Status 'Skipped' -Message 'Skipped (no API token)'))
}

# ---- Check 6: Workspace Capacity ----
if ($token -and $workspace) {
    if ($workspace.capacityId) {
        $results.Add((New-CheckResult -Category 'Workspace' -Check 'Capacity Assignment' `
            -Status 'Pass' -Message "Capacity assigned: $($workspace.capacityId)"))
    }
    else {
        $results.Add((New-CheckResult -Category 'Workspace' -Check 'Capacity Assignment' `
            -Status 'Fail' -Message 'No capacity assigned to workspace' `
            -Remediation 'Assign workspace to an F2+ or P1+ capacity in the Admin Portal'))
    }
}

# ---- Check 7: List Items to Find Data Agents ----
if ($token) {
    try {
        $headers = @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' }
        $itemsUri = "https://api.fabric.microsoft.com/v1/workspaces/$WorkspaceId/items"
        $items = Invoke-RestMethod -Uri $itemsUri -Headers $headers -Method Get -ErrorAction Stop

        $dataAgents = $items.value | Where-Object { $_.type -eq 'DataAgent' -or $_.type -eq 'AISkill' }

        if ($dataAgents -and $dataAgents.Count -gt 0) {
            $results.Add((New-CheckResult -Category 'Data Agent' -Check 'Existing Agents' `
                -Status 'Info' -Message "Found $($dataAgents.Count) data agent(s) in workspace"))
            foreach ($agent in $dataAgents) {
                Write-Verbose "  Agent: $($agent.displayName) | Type: $($agent.type) | ID: $($agent.id)"
            }
        }
        else {
            $results.Add((New-CheckResult -Category 'Data Agent' -Check 'Existing Agents' `
                -Status 'Info' -Message 'No data agents found in workspace (expected if creating a new one)'))
        }

        # Check for data sources
        $lakehouses = $items.value | Where-Object { $_.type -eq 'Lakehouse' }
        $warehouses = $items.value | Where-Object { $_.type -eq 'Warehouse' -or $_.type -eq 'SQLEndpoint' }
        $kqlDbs = $items.value | Where-Object { $_.type -eq 'KQLDatabase' }
        $semanticModels = $items.value | Where-Object { $_.type -eq 'SemanticModel' }

        $dsCount = ($lakehouses.Count + $warehouses.Count + $kqlDbs.Count + $semanticModels.Count)
        if ($dsCount -gt 0) {
            $results.Add((New-CheckResult -Category 'Data Sources' -Check 'Available Sources' `
                -Status 'Pass' `
                -Message "Found $dsCount potential data source(s): $($lakehouses.Count) lakehouse(s), $($warehouses.Count) warehouse(s), $($kqlDbs.Count) KQL DB(s), $($semanticModels.Count) semantic model(s)"))
        }
        else {
            $results.Add((New-CheckResult -Category 'Data Sources' -Check 'Available Sources' `
                -Status 'Warning' `
                -Message 'No lakehouses, warehouses, KQL databases, or semantic models found in this workspace' `
                -Remediation 'Create or add data sources to the workspace, or add data sources from other workspaces via OneLake catalog'))
        }
    }
    catch {
        $results.Add((New-CheckResult -Category 'Data Agent' -Check 'Item Listing' `
            -Status 'Warning' -Message "Could not list workspace items: $_"))
    }
}

# ---- Tenant Settings Reminder ----
$results.Add((New-CheckResult -Category 'Tenant Settings' -Check 'Manual Verification Required' `
    -Status 'Info' `
    -Message 'Tenant settings cannot be read via REST API by non-admin users. Verify manually in Admin Portal.' `
    -Remediation 'See references/tenant-settings-checklist.md for the complete checklist'))

#endregion

#region Output

Write-Host "`n----------------------------------------" -ForegroundColor Cyan
Write-Host " Results Summary" -ForegroundColor Cyan
Write-Host "----------------------------------------`n" -ForegroundColor Cyan

foreach ($r in $results) {
    Write-CheckResult -Result $r
}

$passCount = ($results | Where-Object Status -eq 'Pass').Count
$failCount = ($results | Where-Object Status -eq 'Fail').Count
$warnCount = ($results | Where-Object Status -eq 'Warning').Count

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Total: $($results.Count) checks | Pass: $passCount | Fail: $failCount | Warn: $warnCount" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

if ($OutputFormat -eq 'Json') {
    $results | ConvertTo-Json -Depth 3 | Write-Output
}
elseif ($OutputFormat -eq 'Markdown') {
    Write-Output "# Fabric Data Agent Diagnostic Report"
    Write-Output ""
    Write-Output "| Category | Check | Status | Message |"
    Write-Output "|----------|-------|--------|---------|"
    foreach ($r in $results) {
        Write-Output "| $($r.Category) | $($r.Check) | $($r.Status) | $($r.Message) |"
    }
}

if ($failCount -gt 0) {
    Write-Host "Action required: $failCount check(s) failed. Review remediation steps above." -ForegroundColor Red
    exit 1
}

exit 0

#endregion
