#!/bin/bash
# resolve-chain.sh - Resolve a target chain_id to its Blockscout instance via Chainscout.
#
# Generated by scripts/generate-evm-atlas.mjs. Edit skills/evm-atlas/references/atlas-overlays.json instead.
#
# Usage: resolve-chain.sh <target_chain_id>
#
# Outputs key=value lines on stdout:
#   chain_id=<int>
#   name=<string>
#   native_currency=<symbol>
#   instance_url=<url, ends in />
#   hosted_by=<blockscout|other>
#   is_testnet=<true|false>
#   layer=<int|>
#   rollup_type=<string|>
#
# No API key required. Source: https://chains.blockscout.com/
# Scope is intentionally limited to skills/evm-atlas/references/generated/target-mainnets.json.

set -eu

if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
  echo "Usage: resolve-chain.sh <chain_id>" >&2
  exit 1
fi

chain_id="$1"

target_name_pattern() {
  case "$1" in
    2741) printf '%s\n' 'Abstract' ;;
    42161) printf '%s\n' 'Arbitrum' ;;
    42170) printf '%s\n' 'Arbitrum Nova' ;;
    43114) printf '%s\n' 'Avalanche' ;;
    8453) printf '%s\n' 'Base' ;;
    80094) printf '%s\n' 'Berachain' ;;
    81457) printf '%s\n' 'Blast' ;;
    56) printf '%s\n' 'BNB|BSC|Smart Chain' ;;
    42220) printf '%s\n' 'Celo' ;;
    88888) printf '%s\n' 'Chiliz' ;;
    1116) printf '%s\n' 'Core' ;;
    1) printf '%s\n' 'Ethereum' ;;
    250) printf '%s\n' 'Fantom' ;;
    314) printf '%s\n' 'Filecoin|Filecoin Virtual Machine|FVM' ;;
    252) printf '%s\n' 'Fraxtal' ;;
    100) printf '%s\n' 'Gnosis' ;;
    999) printf '%s\n' 'HyperEVM|Hyper' ;;
    4689) printf '%s\n' 'IoTeX' ;;
    1890) printf '%s\n' 'Lightlink|LightLink' ;;
    59144) printf '%s\n' 'Linea' ;;
    34443) printf '%s\n' 'Mode' ;;
    143) printf '%s\n' 'Monad' ;;
    2818) printf '%s\n' 'Morph' ;;
    10) printf '%s\n' 'OP|Optimism' ;;
    137) printf '%s\n' 'Polygon' ;;
    4663) printf '%s\n' 'Robinhood Chain' ;;
    2020) printf '%s\n' 'Ronin' ;;
    534352) printf '%s\n' 'Scroll' ;;
    1329) printf '%s\n' 'Sei' ;;
    146) printf '%s\n' 'Sonic' ;;
    50104) printf '%s\n' 'Sophon' ;;
    5330) printf '%s\n' 'Superseed' ;;
    167000) printf '%s\n' 'Taiko|Alethia' ;;
    130) printf '%s\n' 'Unichain' ;;
    480) printf '%s\n' 'World' ;;
    50) printf '%s\n' 'XDC' ;;
    324) printf '%s\n' 'ZKsync' ;;
    7777777) printf '%s\n' 'Zora' ;;
    *)
      return 1
      ;;
  esac
}

expected_pattern=$(target_name_pattern "$chain_id") || {
  echo "Error: chain_id=$chain_id is outside the evm-atlas target list." >&2
  echo "Ask the user to file a feature request in https://github.com/PaulRBerg/agent-skills" >&2
  exit 2
}

resp=$(curl -fsS "https://chains.blockscout.com/api/chains/$chain_id" 2>/dev/null) || {
  echo "Error: Chainscout request failed for chain_id=$chain_id" >&2
  exit 1
}

sval() { printf '%s' "$resp" | grep -o "\"$1\":\"[^\"]*\"" | head -1 | sed 's/.*:"\(.*\)"/\1/'; }
nval() { printf '%s' "$resp" | grep -o "\"$1\":[0-9]*" | head -1 | grep -o '[0-9]*'; }
bval() { printf '%s' "$resp" | grep -oE "\"$1\":(true|false)" | head -1 | sed 's/.*://'; }

name=$(sval "name")
if [ -z "$name" ]; then
  echo "Error: chain_id=$chain_id not found in Chainscout" >&2
  exit 1
fi
if ! printf '%s' "$name" | grep -Eiq "$expected_pattern"; then
  echo "Error: Chainscout returned name=$name for target chain_id=$chain_id; expected match=$expected_pattern" >&2
  echo "Refusing to use a non-target Chainscout registry match." >&2
  exit 1
fi

native=$(sval "native_currency")
# "url" only appears inside explorers[]; the first is the primary explorer.
instance=$(printf '%s' "$resp" | grep -o '"url":"[^"]*"' | head -1 | sed 's/.*:"\(.*\)"/\1/')
hosted=$(sval "hostedBy")
testnet=$(bval "isTestnet")
layer=$(nval "layer")
rollup=$(sval "rollupType")

cat <<EOF
chain_id=$chain_id
name=$name
native_currency=$native
instance_url=$instance
hosted_by=$hosted
is_testnet=$testnet
layer=$layer
rollup_type=$rollup
EOF
