"""Regression tests for the spatial-statistics helpers exposed by the CLI."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest

SKILL_DIR = Path(__file__).resolve().parents[1]
FIXTURE = SKILL_DIR / "fixtures" / "squidpy_v1_6_co_occurrence.json"
sys.path.insert(0, str(SKILL_DIR))

import spatial_transcriptomics as st


def test_knn_excludes_the_query_index_when_coordinates_are_duplicated():
    coords = np.array([[0.0, 0.0], [0.0, 0.0], [1.0, 0.0]])
    indices = st.knn_indices(coords, 2)
    assert indices.shape == (3, 2)
    assert np.all(indices != np.arange(coords.shape[0])[:, None])


def test_moran_i_of_a_constant_gene_is_undefined():
    indices = np.array([[1], [0]], dtype=int)
    assert np.isnan(st.moran_i(np.array([4.0, 4.0]), indices))


@pytest.mark.parametrize(
    "values",
    [np.full(3, 0.1), np.log1p(np.full(10, 1e4 / 3))],
    ids=["three_tenths", "log_normalised_ten_spots"],
)
def test_moran_i_of_a_constant_gene_is_undefined_when_its_mean_is_inexact(values):
    # (0.1 + 0.1 + 0.1) / 3 is 0.10000000000000002, so centring a constant can
    # leave the same tiny residual at every spot instead of zeros.
    n_spots = len(values)
    ring = np.array([[(i + 1) % n_spots] for i in range(n_spots)], dtype=int)
    assert np.isnan(st.moran_i(values, ring))


def test_nhood_enrichment_marks_a_zero_variance_null_as_undefined():
    # Every permutation produces the same directed A->A count, so its null SD is 0.
    indices = np.array([[1], [0]], dtype=int)
    clusters, zscores, _ = st.nhood_enrichment(
        indices, np.array(["A", "A"]), n_perms=4, seed=7
    )
    assert clusters == ["A"]
    assert np.isnan(zscores[0, 0])


def test_co_occurrence_is_cumulative_and_uses_eligible_pair_marginals():
    # At r=1.1, only A->B and B->A are eligible.  The eligible target marginal
    # is therefore 1/2 for each cluster, so both conditional/marginal ratios are 2.
    # A global-frequency baseline would give A->B = 1.5 instead of 2 here.
    # The fixture was generated by pinned Squidpy v1.6.0.  Squidpy's leading
    # zero is an interval baseline; this API accepts its emitted radii directly.
    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))
    scores, radii, clusters = st.co_occurrence(
        np.asarray(fixture["coordinates"]),
        np.asarray(fixture["labels"]),
        radii=fixture["radii"],
    )
    assert fixture["axis_order"] == ["source_cluster", "target_cluster", "radius"]
    assert clusters == fixture["clusters"]
    np.testing.assert_allclose(radii, fixture["radii"])
    np.testing.assert_allclose(scores, fixture["scores"])


def test_co_occurrence_rejects_non_finite_coordinates():
    with pytest.raises(ValueError, match="finite"):
        st.co_occurrence(np.array([[0.0, 0.0], [np.nan, 1.0]]), np.array(["A", "B"]))


def test_moran_and_observed_nhood_counts_match_pinned_squidpy_fixture():
    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))["moran_and_nhood"]
    graph = np.asarray(fixture["knn_indices"], dtype=int)
    values = np.asarray(fixture["values"], dtype=float)
    labels = np.asarray(fixture["labels"])
    assert st.moran_i(values, graph) == pytest.approx(fixture["moran_i"])
    np.testing.assert_array_equal(
        st.neighbor_pair_counts(graph, labels, fixture["nhood_clusters"]),
        fixture["nhood_observed_counts"],
    )


def test_co_occurrence_marks_an_empty_radius_as_undefined():
    coords = np.array([[0.0, 0.0], [3.0, 0.0], [6.0, 0.0]])
    scores, radii, _ = st.co_occurrence(
        coords, np.array(["A", "B", "B"]), radii=[0.5, 3.1]
    )
    assert radii.tolist() == [0.5, 3.1]
    assert np.isnan(scores[:, :, 0]).all()
    assert np.isfinite(scores[:, :, 1]).all()


def test_nhood_enrichment_is_seed_reproducible():
    graph = np.array([[1, 2], [0, 2], [0, 1], [2, 1]], dtype=int)
    labels = np.array(["A", "A", "B", "B"])
    first = st.nhood_enrichment(graph, labels, n_perms=11, seed=19)
    second = st.nhood_enrichment(graph, labels, n_perms=11, seed=19)
    assert first[0] == second[0]
    np.testing.assert_allclose(first[1], second[1], equal_nan=True)
    np.testing.assert_array_equal(first[2], second[2])
