#!/bin/sh
# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: c3ab2123a34ab0da697d688ec1418c9181169a16f8c072aede4855b6fcf48b3a
set -eu
fail() { printf '%s\n' "$*" >&2; exit 1; }
scope=repo
case $# in
    0) ;;
    1) [ "$1" = --user ] || fail 'Usage: install.sh [--user]'; scope=user ;;
    *) fail 'Usage: install.sh [--user]' ;;
esac
base=$(pwd -P)
if [ "$scope" = user ]; then
    [ -n "${HOME:-}" ] || fail 'HOME is required for --user'
    base=$(CDPATH= cd -- "$HOME" && pwd -P)
    target="$base/.agents/skills"
else
    target="$base/.agents/skills"
fi
source="$(dirname -- "$0")/../agent-skills"
[ ! -L "$source" ] || fail 'Symlink source root'
source=$(CDPATH= cd -- "$source" && pwd -P)
if command -v sha256sum >/dev/null 2>&1; then
    checksum() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1; then
    checksum() { shasum -a 256 "$@"; }
else
    fail 'SHA256 verification requires sha256sum or shasum'
fi
checksums=$(cat <<'OMH_CHECKSUMS'
e2f53aaa3bf8d791571331103dcbbe8181d70f4eb6848ae5ff78b873c1e1307a  omh-accessibility-audit/SKILL.md
cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469  omh-accessibility-audit/references/a11y-rules.md
8e0fbabbfc155a2747d7a79988f14cc81e3985cfc61e6c84feab7efe779c2cc1  omh-adversarial-consensus/SKILL.md
e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89  omh-adversarial-consensus/references/consensus-protocol.md
524e3d219ade7d453a5e945b040ef255493e816a3deec6ad45bc1f1b48123114  omh-agent-debug/SKILL.md
56cefe9ff105cd9f625990b333c4034fc0aa5931b335f25ea4a6c0a976c79a18  omh-agent-ops-review/SKILL.md
d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291  omh-agent-ops-review/references/instrumentation-ladder.md
c2be8f464b39907096b4f36ebc8aabf86fc10da446dda86bfd10696297e706c5  omh-ai-slop-cleaner/SKILL.md
d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d  omh-ai-slop-cleaner/references/cleanup-passes.md
efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5  omh-ai-slop-cleaner/references/prose-lexicon.md
bf68a6134d072c66055411bf45fb34284ef1eb5705be023777e434c59b57f7f2  omh-apple-design/SKILL.md
09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26  omh-apple-design/references/materials-and-accessibility.md
4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0  omh-apple-design/references/platform-foundations.md
835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd  omh-apple-design/references/product-visual-production.md
c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604  omh-apple-design/references/review-playbook.md
81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e  omh-apple-design/references/web-production-libraries.md
5438e0bf5e21a7960853a779be1664cd5e7c2bc3d718396f632b457a45cd6c8a  omh-application-threat-model/SKILL.md
ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e  omh-application-threat-model/references/threat-model-method.md
9363fcc5edc4eed137d3d00b4c047b0c0041ec5737351f9c08316cd1c5ca8d9e  omh-apps/SKILL.md
dcd26966b2e818b0f93628ed585f91ab44eb39a7c9ce949d59f5baf6d43c65a8  omh-ask/SKILL.md
bc138edb798d567b1c1b69991c1f6e5b921310ec7f788e645ab87d54e94d9231  omh-award-bar-score/SKILL.md
3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50  omh-award-bar-score/references/award-judging-model.md
b8800e59de781e97bf7b203b1521866cbddbcf2772e2c1e4db49ed40adb1855f  omh-backend/SKILL.md
843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9  omh-backend/references/consumer-impact.md
e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054  omh-backend/references/schema-migration.md
984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5  omh-backend/references/service-contract.md
a66326e42cf564dfca9dcc97af35396614d2db287339894c81fb0983851971f4  omh-build-failure-triage/SKILL.md
37a55012a5a508e3299ba125a5c55e15636a919b28cfef61bfecd125daba5ced  omh-cancel/SKILL.md
46393359af8f9d080dfa9b87079cb9ccf2dd2da4026ae3c392ee5abe8b9222a6  omh-code-review/SKILL.md
6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424  omh-code-review/references/review-dispatch.md
fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f  omh-code-review/references/review-lenses.md
9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db  omh-code-review/references/review-response.md
99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be  omh-code-review/references/smell-baseline.md
5518df4ea48748370661d582f58f808cc4b87c182da18620c29cb8baedbee435  omh-codebase-onboarding/SKILL.md
efad9e3ef75030c1e08ef270167852c71a98ef851872df5eabe2747a919dc7ed  omh-codebase-uml/SKILL.md
78d5bef95a71d50afd92102b32210d49a2e6b12b3de938d6e03325067b7d34a1  omh-codegraph-refresh/SKILL.md
19685de27bd0f1aa64215ada55f164a124cebd9d4da9b19d2ac225cd1f9add88  omh-content-operator/SKILL.md
1d6707312644eadfcb14140d57609ee927a67d8bb1bcf95697d5aef456a03078  omh-context-budget-review/SKILL.md
bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590  omh-context-budget-review/references/cache-placement.md
aad205ac9e4889a9494dbf4c7564db1f7ce31c81e8626eb8a87d28a86e718e6a  omh-cto-loop/SKILL.md
ad0c67442ac9057ae505f34696f3d62174f0ddb2ec544dc68423ebb7700ca19f  omh-curriculum-design/SKILL.md
5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b  omh-curriculum-design/references/procedure.md
7a2cc113187b675030e9e47b42310ed292fa131839a1f716d0c47ef56d5d0fb0  omh-data-analysis/SKILL.md
02daa0c598e221c2345d047900a77489c5e9c6d7a9e1f10cf6626d17a478d94b  omh-decide/SKILL.md
5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae  omh-decide/references/capacity-planning.md
4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d  omh-decide/references/decision-records.md
9d28916045f5907703294f0dd21d8008722fee58f5fa55e2a392e757c920ffec  omh-decision-prototype/SKILL.md
53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88  omh-decision-prototype/references/procedure.md
4446b294e7265e0b24e42319691137e887a351b4a2385da6a436448d310e3a09  omh-decision-recall/SKILL.md
814984ab322ddd92ee6f2f0f36c06ef46c58b49e6cc6866e97750fcfa406d29e  omh-deliverable-package/SKILL.md
6df483f7ad5541a726baf1b096f2a83e1e6edd26c544ea705e8967c45b82f360  omh-deploy-and-monitor/SKILL.md
dcaecaf6d5c54cead0812e26c8938afddc1eccfaa57fdf5e4d2646ccf4d455ba  omh-design-orchestration/SKILL.md
d0e240dea31cf49c9c1299c2f16b0d7aeca5654ceacf11b853497729a19b95aa  omh-design-quality-gate/SKILL.md
7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae  omh-design-quality-gate/references/design-critique-rubric.md
0fd7d325b742b24c591e6d78809eb36a5ae3d7478e91dce73dc00350511e58a8  omh-docs/SKILL.md
c9c7deb0d1403d8bb8822b2b7b6a63d380ac1615ac98bda8e2eeafa9dc3e640c  omh-external-connector-readiness/SKILL.md
b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3  omh-external-connector-readiness/references/memory-provider-trial.md
918259936d49166f99130a2142aa2983f4fb1bedfe151b24e5c8661dac2ad14e  omh-failure-signal-audit/SKILL.md
b5dfceef974b9b80e9aa5dfd1c921e6b36d3fbc084e5e34823fb3058c5433632  omh-feedback-triage/SKILL.md
9bd678445a9038132b715fbc041b01c4701ba48ba5f2dcdc1205aafce794a400  omh-files/SKILL.md
5b51542aabaf3f55bf7e9d79527afb5e392fdf865a0a39cf378c3b00856cc6d6  omh-finance-analysis/SKILL.md
0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c  omh-finance-analysis/references/procedure.md
c72e827d03355e14b684de5772b57bd168798d869ce5ed2b46d1818a48cc833b  omh-frontend-refactor/SKILL.md
ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f  omh-frontend-refactor/references/refactor-passes.md
04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4  omh-frontend-refactor/references/state-discipline.md
a965087a30bc298f8171f11a54a8368d04d8e984c80f44ca21a65e07edc6cf0c  omh-frontend/SKILL.md
5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c  omh-frontend/references/design-system-contract.md
b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf  omh-frontend/references/reference-token-extraction.md
ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09  omh-frontend/references/screenshot-loop.md
605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245  omh-frontend/references/scroll-motion-libraries.md
2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7  omh-frontend/references/taste-foundations.md
13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e  omh-frontend/references/tui-craft.md
7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b  omh-frontend/references/web-vitals-budgets.md
40a6e5c7114ea565a2e640663b05fe128ad47c9c1d125211cfc58957b8e84163  omh-github-event-ops/SKILL.md
ee5dfe3343d5deafe3aff7f49fcbfcd69feb42aa41bfb8a71501a45a057eedad  omh-github-issue-intake/SKILL.md
f76e9eda71d216b5784947e732e1a818daa3af7ab205b2c7a64f3be95b122768  omh-harness-session-inventory/SKILL.md
005a6c5691a98d9876da7c954b8c060840f1470ad0848bf75ec52d3ffaac6797  omh-idea-to-deploy/SKILL.md
dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7  omh-idea-to-deploy/references/project-bootstrap.md
47aba256922c5ce822f57cbc63bc184c833bd97718009c626f1db0ab8c2e669c  omh-image-cards/SKILL.md
d357a82bf576620aac11270f65caea1f232bdb9c15515f52f31630854007aa63  omh-inference-serving/SKILL.md
31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0  omh-inference-serving/references/serving-bench.md
da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e  omh-inference-serving/references/serving-runbooks.md
db74247a2a84274de14feeb7097b75c5061a3565ccc37a4de42245c15177ea64  omh-instinct-ledger/SKILL.md
cc30647c56414741ee70528c2ea3300f5115d3009f7f0ff833d6737845b2bdb4  omh-jit-learn/SKILL.md
20c1242de604e9fcb01727b400efa5daf128a70dc133210c8aa37af9d2297509  omh-legal-compliance-review/SKILL.md
a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1  omh-legal-compliance-review/references/negotiation-preparation.md
670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58  omh-legal-compliance-review/references/procedure.md
e19e3cb197142fc4a41f658ac301547d529eb54698ac1d7a07a06ab439fe14d6  omh-lifecycle-growth/SKILL.md
7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de  omh-lifecycle-growth/references/procedure.md
96542b38eba9dba656569cefd1f4109d51efd8d29a8e0e2bd9888ff94a576030  omh-live-incident-response/SKILL.md
8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7  omh-live-incident-response/references/incident-command-method.md
273149a89d360c7f05f6d4b9fd16391d2e337355130d41142ae18d0dc06520e0  omh-live-info/SKILL.md
af9664d1ad110e70fbeb85ac4b671a7f1b9db2a80dce0037e9731118f9db65a1  omh-llm-app-dev/SKILL.md
35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149  omh-llm-app-dev/references/build-rails.md
959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd  omh-llm-app-dev/references/eval-harness.md
e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca  omh-llm-app-dev/references/public-board.md
7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816  omh-llm-app-dev/references/stateful-contracts.md
045d53ee5c967b73a046214497d562124d55ab3dd85b4f15ed2fc19bae0acc00  omh-localization-review/SKILL.md
b899c87d480f65f0256892a237be627239aa17e7fc7d48506ab756f3af3b1dea  omh-materials-package/SKILL.md
1561b2e4a0f463e3df42b44cdffc75f287a0d072d8b14b0c2119c03a60689b3a  omh-media-input/SKILL.md
a0d9368ad65e0b4e4f5a88eb19e7006b57b31a5b792e29153c2d9c14d4554cb8  omh-meeting-brief/SKILL.md
4b055fc91ae8c729ec1190c8ba7a4c9baaba04c12dfb524df1781d25fc818c3f  omh-memory-new/SKILL.md
3c4e71bc5956eb9c0bc4c16efe8de1da624e7ce44bf2ed05fec73e2f9ae80ffa  omh-native-debugging/SKILL.md
3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d  omh-native-debugging/references/native-debug-loop.md
709ea7a6884876085ddd311d90b35bf8c4a5fcc402c16be42252264b1635be26  omh-operating-rhythm/SKILL.md
a0f56e0eb499d60db06aea84e90d1e015af188ed3c141c4dad7e35a5dfc5b714  omh-ops-observability-card/SKILL.md
f960b22abb3ba333185522d51784bee0b422e7c71a2b8db037a24c96860632f6  omh-ops-review/SKILL.md
248c2883d8f1b0e89f71171eb03a1320ec9ae13b8bcca8e81967bca30cc39c48  omh-paper-learning/SKILL.md
59fd3e99633ac4bc24d684a2f2716eb4b8ec812f684ac84f3661b6756b175dbb  omh-people-ops/SKILL.md
8f7e007abb95f11b89d28ccb9d411fa1cb1ae622fa53a80616ec62e061347e75  omh-physical-device-readiness/SKILL.md
0f18e6cf54a5702c29f9c861f8ff1dcc72122509cabe1c31dff47ac3c310c88f  omh-plan/SKILL.md
577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da  omh-plan/references/project-constitution.md
1a72eb4128ce3f927b52f9e021058cf21a251a9d9bf4ea76046000b7795d3872  omh-product-brief/SKILL.md
62538e5fdc785e4cb548a095fdc503da733b76786bc36659097c4229aec9e183  omh-product-discovery-validation/SKILL.md
c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a  omh-product-discovery-validation/references/procedure.md
ec5da405340df1a55a9ad7a7a204166531651c37787d5cb6ce22d78de92c801a  omh-production-audit/SKILL.md
86f5720e1d6fe0220d50cee42dc1ae75ee43061270523872992a5833eab6ad9a  omh-provider-profile-posture/SKILL.md
2488255f6aa62165715be681236798606b9992e8a3142ad2bbc3f4d750a9bc99  omh-refactor-plan/SKILL.md
b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0  omh-refactor-plan/references/dependency-upgrade.md
492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035  omh-refactor-plan/references/refactor-phases.md
dfdefd90bd970f3d40612608c15b2c1348f06e91139df4e42c473405361beb37  omh-reliability-review/SKILL.md
b5ecc307c054283b5d552f6345645a41c318d9c81cf5e1cb9ea2746348ad283c  omh-report-package/SKILL.md
d7b385f0f73fe20ee5fda984acde6229b9a663486608991eb1f097a001146392  omh-research-brief/SKILL.md
5bea104f358c4c851fa23fe58904a7e7c63c4d4f360c056023675421dfd54947  omh-rules-distill/SKILL.md
5c48f659139e97a8cca57e51fb93a4fe006682689a21cdfa73907e49dd756d44  omh-run-efficiency/SKILL.md
4056366ffd30adee8136e2282ae2bc975a3ac0c0074b80756ea09f6dcbd496ed  omh-running-work-board/SKILL.md
7c658499bafd1de3c54e2f35be322dfe246ea5efecd9627037ea2ca422cdb9f4  omh-rust/SKILL.md
7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844  omh-rust/references/rust-discipline.md
b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768  omh-rust/references/ub-escalation.md
f2ac90ea45684809641ffd7c49b06df5aedc98009babe6470441ba350ab21c15  omh-sales-development/SKILL.md
0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70  omh-sales-development/references/procedure.md
e32cd4a816e7c5a88567ba80df8573be6c4696379be273fbf59336c6680a6b3d  omh-sales-pipeline-review/SKILL.md
ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138  omh-sales-pipeline-review/references/procedure.md
34856dee03f4b3c0215e44e51d15a042cb441c0a58782e6b24e1c4a7edb87d6c  omh-security-safety-review/SKILL.md
2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065  omh-security-safety-review/references/credential-rotation.md
9ea843bc1035bffff5fd6eaac63a6f97f8ca5db4253d4d39b90d419a282c1ebc  omh-skill-health/SKILL.md
83c6fe30254885510c002277e2aada3864739dc514b8b652993150a4f91f26fc  omh-skill-scout/SKILL.md
3fdf0070dd65440488eeeb6d04dc6e98a0021f4e7214d6bd385bef9befeb6526  omh-source-finder/SKILL.md
7773a91fb7258c7f80280266194b6df244492a01585ed150c518714457e0f8c1  omh-support-operations/SKILL.md
b080b6fb79f99a796ff4830641b5509ad464b6d6bd38fdad169b1d418fe59f9e  omh-tech-debt-audit/SKILL.md
7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75  omh-tech-debt-audit/references/debt-dimensions.md
2e195d330ee4284276d8a486891bfaef4626e155130f592d24086b054e768f5f  omh-terminal/SKILL.md
16982df8ecba2fb01c9afea2e540c8b174e4b67740d028287ff8b38ed7b1c43b  omh-toolbelt-readiness/SKILL.md
2e53924ae2593aa5a9de7f8280cd993cba595ad4dacddb9fcfacd0eae69867d0  omh-verification-gate/SKILL.md
91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad  omh-verification-gate/references/generated-artifact-provenance.md
91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19  omh-verification-gate/references/requirement-coverage-map.md
2b27edb565e5f37bb69e7d45bea2df50a499c72a57945ce27562a27122f52c41  omh-visual-qa/SKILL.md
7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759  omh-visual-qa/references/visual-verdict-contract.md
c1c6124525be0a3c95cbf8106088c6a157e8eef6fa4728b9a4ba0b91d71b6b57  omh-voice-input/SKILL.md
bbddec7336589a938f71691b88fcde358fc65467efeeb7731b8cf2927a4afa5c  omh-web-research/SKILL.md
334f1d7edebb4e63134f0938d66dcbb93098902b7d6e8b55b156718fca4b5547  omh-wiki/SKILL.md
6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c  omh-wiki/references/wiki-blueprint.md
656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528  omh-wiki/references/wiki-operations.md
f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e  omh-wiki/references/wiki-patterns.md
2499a100737a79d5d775e38a983971c2ac22fac2d0386de61b65aafcca840fe7  omh-workspace-audit/SKILL.md
7ba238fbd1e2752badc98d36380a4ce2c5701e77f3eba7cf98100fce4a366010  ulw-context/SKILL.md
122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df  ulw-context/references/decision-frontier.md
0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45  ulw-context/references/project-terms.md
553e8f190d148bdb870ae5d0a82276b4dcdab1862a9b7ff0812f909bd8458d15  ulw-interview/SKILL.md
af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a  ulw-interview/references/ambiguity-taxonomy.md
624963ae486aab64f56d0f0781051184a6863a9e1dea898b4a85f0168c02efe9  ulw-loop/SKILL.md
e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f  ulw-loop/references/goal-constraint-discipline.md
1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb  ulw-loop/references/measured-loop-discipline.md
1ae9136c6abef70c11048a5b07ede1d0d10439248058a23237cf32cf8d28964f  ulw-perf/SKILL.md
ccb3d8edce24e74c1a872c3108ad3f3b52c7466b17d705aa97ac0cf2be841a0d  ulw-plan/SKILL.md
1a384bbfcfbb710c7b82e516e4cc98faac6827dd0ce771fe2a01e82da980bd8d  ulw-qa/SKILL.md
b96f347662adbdadc2ab6e8a3b1f7935a879acee98eb5d093dc7f343294b8b80  ulw-research/SKILL.md
466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac  ulw-research/references/briefing-format.md
104021f9f990e8b0b4940f71b295bfcbc57afc5e2c34e37cd46791e06ffc07e9  ulw-work/SKILL.md
b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac  ulw-work/references/dependency-topology.md
OMH_CHECKSUMS
)
paths=$(cat <<'OMH_PATHS'
omh-accessibility-audit/SKILL.md
omh-accessibility-audit/references/a11y-rules.md
omh-adversarial-consensus/SKILL.md
omh-adversarial-consensus/references/consensus-protocol.md
omh-agent-debug/SKILL.md
omh-agent-ops-review/SKILL.md
omh-agent-ops-review/references/instrumentation-ladder.md
omh-ai-slop-cleaner/SKILL.md
omh-ai-slop-cleaner/references/cleanup-passes.md
omh-ai-slop-cleaner/references/prose-lexicon.md
omh-apple-design/SKILL.md
omh-apple-design/references/materials-and-accessibility.md
omh-apple-design/references/platform-foundations.md
omh-apple-design/references/product-visual-production.md
omh-apple-design/references/review-playbook.md
omh-apple-design/references/web-production-libraries.md
omh-application-threat-model/SKILL.md
omh-application-threat-model/references/threat-model-method.md
omh-apps/SKILL.md
omh-ask/SKILL.md
omh-award-bar-score/SKILL.md
omh-award-bar-score/references/award-judging-model.md
omh-backend/SKILL.md
omh-backend/references/consumer-impact.md
omh-backend/references/schema-migration.md
omh-backend/references/service-contract.md
omh-build-failure-triage/SKILL.md
omh-cancel/SKILL.md
omh-code-review/SKILL.md
omh-code-review/references/review-dispatch.md
omh-code-review/references/review-lenses.md
omh-code-review/references/review-response.md
omh-code-review/references/smell-baseline.md
omh-codebase-onboarding/SKILL.md
omh-codebase-uml/SKILL.md
omh-codegraph-refresh/SKILL.md
omh-content-operator/SKILL.md
omh-context-budget-review/SKILL.md
omh-context-budget-review/references/cache-placement.md
omh-cto-loop/SKILL.md
omh-curriculum-design/SKILL.md
omh-curriculum-design/references/procedure.md
omh-data-analysis/SKILL.md
omh-decide/SKILL.md
omh-decide/references/capacity-planning.md
omh-decide/references/decision-records.md
omh-decision-prototype/SKILL.md
omh-decision-prototype/references/procedure.md
omh-decision-recall/SKILL.md
omh-deliverable-package/SKILL.md
omh-deploy-and-monitor/SKILL.md
omh-design-orchestration/SKILL.md
omh-design-quality-gate/SKILL.md
omh-design-quality-gate/references/design-critique-rubric.md
omh-docs/SKILL.md
omh-external-connector-readiness/SKILL.md
omh-external-connector-readiness/references/memory-provider-trial.md
omh-failure-signal-audit/SKILL.md
omh-feedback-triage/SKILL.md
omh-files/SKILL.md
omh-finance-analysis/SKILL.md
omh-finance-analysis/references/procedure.md
omh-frontend-refactor/SKILL.md
omh-frontend-refactor/references/refactor-passes.md
omh-frontend-refactor/references/state-discipline.md
omh-frontend/SKILL.md
omh-frontend/references/design-system-contract.md
omh-frontend/references/reference-token-extraction.md
omh-frontend/references/screenshot-loop.md
omh-frontend/references/scroll-motion-libraries.md
omh-frontend/references/taste-foundations.md
omh-frontend/references/tui-craft.md
omh-frontend/references/web-vitals-budgets.md
omh-github-event-ops/SKILL.md
omh-github-issue-intake/SKILL.md
omh-harness-session-inventory/SKILL.md
omh-idea-to-deploy/SKILL.md
omh-idea-to-deploy/references/project-bootstrap.md
omh-image-cards/SKILL.md
omh-inference-serving/SKILL.md
omh-inference-serving/references/serving-bench.md
omh-inference-serving/references/serving-runbooks.md
omh-instinct-ledger/SKILL.md
omh-jit-learn/SKILL.md
omh-legal-compliance-review/SKILL.md
omh-legal-compliance-review/references/negotiation-preparation.md
omh-legal-compliance-review/references/procedure.md
omh-lifecycle-growth/SKILL.md
omh-lifecycle-growth/references/procedure.md
omh-live-incident-response/SKILL.md
omh-live-incident-response/references/incident-command-method.md
omh-live-info/SKILL.md
omh-llm-app-dev/SKILL.md
omh-llm-app-dev/references/build-rails.md
omh-llm-app-dev/references/eval-harness.md
omh-llm-app-dev/references/public-board.md
omh-llm-app-dev/references/stateful-contracts.md
omh-localization-review/SKILL.md
omh-materials-package/SKILL.md
omh-media-input/SKILL.md
omh-meeting-brief/SKILL.md
omh-memory-new/SKILL.md
omh-native-debugging/SKILL.md
omh-native-debugging/references/native-debug-loop.md
omh-operating-rhythm/SKILL.md
omh-ops-observability-card/SKILL.md
omh-ops-review/SKILL.md
omh-paper-learning/SKILL.md
omh-people-ops/SKILL.md
omh-physical-device-readiness/SKILL.md
omh-plan/SKILL.md
omh-plan/references/project-constitution.md
omh-product-brief/SKILL.md
omh-product-discovery-validation/SKILL.md
omh-product-discovery-validation/references/procedure.md
omh-production-audit/SKILL.md
omh-provider-profile-posture/SKILL.md
omh-refactor-plan/SKILL.md
omh-refactor-plan/references/dependency-upgrade.md
omh-refactor-plan/references/refactor-phases.md
omh-reliability-review/SKILL.md
omh-report-package/SKILL.md
omh-research-brief/SKILL.md
omh-rules-distill/SKILL.md
omh-run-efficiency/SKILL.md
omh-running-work-board/SKILL.md
omh-rust/SKILL.md
omh-rust/references/rust-discipline.md
omh-rust/references/ub-escalation.md
omh-sales-development/SKILL.md
omh-sales-development/references/procedure.md
omh-sales-pipeline-review/SKILL.md
omh-sales-pipeline-review/references/procedure.md
omh-security-safety-review/SKILL.md
omh-security-safety-review/references/credential-rotation.md
omh-skill-health/SKILL.md
omh-skill-scout/SKILL.md
omh-source-finder/SKILL.md
omh-support-operations/SKILL.md
omh-tech-debt-audit/SKILL.md
omh-tech-debt-audit/references/debt-dimensions.md
omh-terminal/SKILL.md
omh-toolbelt-readiness/SKILL.md
omh-verification-gate/SKILL.md
omh-verification-gate/references/generated-artifact-provenance.md
omh-verification-gate/references/requirement-coverage-map.md
omh-visual-qa/SKILL.md
omh-visual-qa/references/visual-verdict-contract.md
omh-voice-input/SKILL.md
omh-web-research/SKILL.md
omh-wiki/SKILL.md
omh-wiki/references/wiki-blueprint.md
omh-wiki/references/wiki-operations.md
omh-wiki/references/wiki-patterns.md
omh-workspace-audit/SKILL.md
ulw-context/SKILL.md
ulw-context/references/decision-frontier.md
ulw-context/references/project-terms.md
ulw-interview/SKILL.md
ulw-interview/references/ambiguity-taxonomy.md
ulw-loop/SKILL.md
ulw-loop/references/goal-constraint-discipline.md
ulw-loop/references/measured-loop-discipline.md
ulw-perf/SKILL.md
ulw-plan/SKILL.md
ulw-qa/SKILL.md
ulw-research/SKILL.md
ulw-research/references/briefing-format.md
ulw-work/SKILL.md
ulw-work/references/dependency-topology.md
OMH_PATHS
)
# Reject extra files and links rather than silently installing an unverified tree.
[ -z "$(find "$source" ! -type f ! -type d -print)" ] || fail 'Unsupported source entry (including symlink)'
actual=$(cd "$source" && find . -type f -print | LC_ALL=C sort)
expected=$(printf '%s\n' "$paths" | while IFS= read -r path; do printf './%s\n' "$path"; done)
[ "$actual" = "$expected" ] || fail 'Source file inventory mismatch'
verify() {
    printf '%s\n' "$checksums" | (cd "$1" && checksum -c -) >/dev/null || fail 'Skill digest mismatch'
}
verify "$source"
# Preflight EVERY target before the first write, including the receipt.
# Do not follow destination links.
printf '%s\n' "$paths" '.omh-agent-skills-manifest.json' | while IFS= read -r path; do
    current="$target/$path"
    while [ "$current" != "$base" ]; do
        [ ! -L "$current" ] || fail "Symlink destination: $current"
        current=${current%/*}
        [ -n "$current" ] || current=/
    done
    [ ! -e "$target/$path" ] || [ -f "$target/$path" ] || fail "Not a file: $target/$path"
done
printf '%s\n' "$paths" | while IFS= read -r path; do
    mkdir -p "$target/${path%/*}"
    cp "$source/$path" "$target/$path"
done
verify "$target"
cat > "$target/.omh-agent-skills-manifest.json" <<'OMH_RECEIPT'
{
  "catalog_revision": "ccd713a77273889995f2cafcf6408fa94c80d01561372dd445cd779a51681ffd",
  "files": {
    "omh-accessibility-audit/SKILL.md": "e2f53aaa3bf8d791571331103dcbbe8181d70f4eb6848ae5ff78b873c1e1307a",
    "omh-accessibility-audit/references/a11y-rules.md": "cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469",
    "omh-adversarial-consensus/SKILL.md": "8e0fbabbfc155a2747d7a79988f14cc81e3985cfc61e6c84feab7efe779c2cc1",
    "omh-adversarial-consensus/references/consensus-protocol.md": "e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89",
    "omh-agent-debug/SKILL.md": "524e3d219ade7d453a5e945b040ef255493e816a3deec6ad45bc1f1b48123114",
    "omh-agent-ops-review/SKILL.md": "56cefe9ff105cd9f625990b333c4034fc0aa5931b335f25ea4a6c0a976c79a18",
    "omh-agent-ops-review/references/instrumentation-ladder.md": "d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291",
    "omh-ai-slop-cleaner/SKILL.md": "c2be8f464b39907096b4f36ebc8aabf86fc10da446dda86bfd10696297e706c5",
    "omh-ai-slop-cleaner/references/cleanup-passes.md": "d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d",
    "omh-ai-slop-cleaner/references/prose-lexicon.md": "efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5",
    "omh-apple-design/SKILL.md": "bf68a6134d072c66055411bf45fb34284ef1eb5705be023777e434c59b57f7f2",
    "omh-apple-design/references/materials-and-accessibility.md": "09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26",
    "omh-apple-design/references/platform-foundations.md": "4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0",
    "omh-apple-design/references/product-visual-production.md": "835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd",
    "omh-apple-design/references/review-playbook.md": "c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604",
    "omh-apple-design/references/web-production-libraries.md": "81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e",
    "omh-application-threat-model/SKILL.md": "5438e0bf5e21a7960853a779be1664cd5e7c2bc3d718396f632b457a45cd6c8a",
    "omh-application-threat-model/references/threat-model-method.md": "ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e",
    "omh-apps/SKILL.md": "9363fcc5edc4eed137d3d00b4c047b0c0041ec5737351f9c08316cd1c5ca8d9e",
    "omh-ask/SKILL.md": "dcd26966b2e818b0f93628ed585f91ab44eb39a7c9ce949d59f5baf6d43c65a8",
    "omh-award-bar-score/SKILL.md": "bc138edb798d567b1c1b69991c1f6e5b921310ec7f788e645ab87d54e94d9231",
    "omh-award-bar-score/references/award-judging-model.md": "3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50",
    "omh-backend/SKILL.md": "b8800e59de781e97bf7b203b1521866cbddbcf2772e2c1e4db49ed40adb1855f",
    "omh-backend/references/consumer-impact.md": "843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9",
    "omh-backend/references/schema-migration.md": "e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054",
    "omh-backend/references/service-contract.md": "984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5",
    "omh-build-failure-triage/SKILL.md": "a66326e42cf564dfca9dcc97af35396614d2db287339894c81fb0983851971f4",
    "omh-cancel/SKILL.md": "37a55012a5a508e3299ba125a5c55e15636a919b28cfef61bfecd125daba5ced",
    "omh-code-review/SKILL.md": "46393359af8f9d080dfa9b87079cb9ccf2dd2da4026ae3c392ee5abe8b9222a6",
    "omh-code-review/references/review-dispatch.md": "6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424",
    "omh-code-review/references/review-lenses.md": "fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f",
    "omh-code-review/references/review-response.md": "9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db",
    "omh-code-review/references/smell-baseline.md": "99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be",
    "omh-codebase-onboarding/SKILL.md": "5518df4ea48748370661d582f58f808cc4b87c182da18620c29cb8baedbee435",
    "omh-codebase-uml/SKILL.md": "efad9e3ef75030c1e08ef270167852c71a98ef851872df5eabe2747a919dc7ed",
    "omh-codegraph-refresh/SKILL.md": "78d5bef95a71d50afd92102b32210d49a2e6b12b3de938d6e03325067b7d34a1",
    "omh-content-operator/SKILL.md": "19685de27bd0f1aa64215ada55f164a124cebd9d4da9b19d2ac225cd1f9add88",
    "omh-context-budget-review/SKILL.md": "1d6707312644eadfcb14140d57609ee927a67d8bb1bcf95697d5aef456a03078",
    "omh-context-budget-review/references/cache-placement.md": "bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590",
    "omh-cto-loop/SKILL.md": "aad205ac9e4889a9494dbf4c7564db1f7ce31c81e8626eb8a87d28a86e718e6a",
    "omh-curriculum-design/SKILL.md": "ad0c67442ac9057ae505f34696f3d62174f0ddb2ec544dc68423ebb7700ca19f",
    "omh-curriculum-design/references/procedure.md": "5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b",
    "omh-data-analysis/SKILL.md": "7a2cc113187b675030e9e47b42310ed292fa131839a1f716d0c47ef56d5d0fb0",
    "omh-decide/SKILL.md": "02daa0c598e221c2345d047900a77489c5e9c6d7a9e1f10cf6626d17a478d94b",
    "omh-decide/references/capacity-planning.md": "5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae",
    "omh-decide/references/decision-records.md": "4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d",
    "omh-decision-prototype/SKILL.md": "9d28916045f5907703294f0dd21d8008722fee58f5fa55e2a392e757c920ffec",
    "omh-decision-prototype/references/procedure.md": "53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88",
    "omh-decision-recall/SKILL.md": "4446b294e7265e0b24e42319691137e887a351b4a2385da6a436448d310e3a09",
    "omh-deliverable-package/SKILL.md": "814984ab322ddd92ee6f2f0f36c06ef46c58b49e6cc6866e97750fcfa406d29e",
    "omh-deploy-and-monitor/SKILL.md": "6df483f7ad5541a726baf1b096f2a83e1e6edd26c544ea705e8967c45b82f360",
    "omh-design-orchestration/SKILL.md": "dcaecaf6d5c54cead0812e26c8938afddc1eccfaa57fdf5e4d2646ccf4d455ba",
    "omh-design-quality-gate/SKILL.md": "d0e240dea31cf49c9c1299c2f16b0d7aeca5654ceacf11b853497729a19b95aa",
    "omh-design-quality-gate/references/design-critique-rubric.md": "7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae",
    "omh-docs/SKILL.md": "0fd7d325b742b24c591e6d78809eb36a5ae3d7478e91dce73dc00350511e58a8",
    "omh-external-connector-readiness/SKILL.md": "c9c7deb0d1403d8bb8822b2b7b6a63d380ac1615ac98bda8e2eeafa9dc3e640c",
    "omh-external-connector-readiness/references/memory-provider-trial.md": "b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3",
    "omh-failure-signal-audit/SKILL.md": "918259936d49166f99130a2142aa2983f4fb1bedfe151b24e5c8661dac2ad14e",
    "omh-feedback-triage/SKILL.md": "b5dfceef974b9b80e9aa5dfd1c921e6b36d3fbc084e5e34823fb3058c5433632",
    "omh-files/SKILL.md": "9bd678445a9038132b715fbc041b01c4701ba48ba5f2dcdc1205aafce794a400",
    "omh-finance-analysis/SKILL.md": "5b51542aabaf3f55bf7e9d79527afb5e392fdf865a0a39cf378c3b00856cc6d6",
    "omh-finance-analysis/references/procedure.md": "0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c",
    "omh-frontend-refactor/SKILL.md": "c72e827d03355e14b684de5772b57bd168798d869ce5ed2b46d1818a48cc833b",
    "omh-frontend-refactor/references/refactor-passes.md": "ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f",
    "omh-frontend-refactor/references/state-discipline.md": "04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4",
    "omh-frontend/SKILL.md": "a965087a30bc298f8171f11a54a8368d04d8e984c80f44ca21a65e07edc6cf0c",
    "omh-frontend/references/design-system-contract.md": "5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c",
    "omh-frontend/references/reference-token-extraction.md": "b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf",
    "omh-frontend/references/screenshot-loop.md": "ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09",
    "omh-frontend/references/scroll-motion-libraries.md": "605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245",
    "omh-frontend/references/taste-foundations.md": "2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7",
    "omh-frontend/references/tui-craft.md": "13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e",
    "omh-frontend/references/web-vitals-budgets.md": "7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b",
    "omh-github-event-ops/SKILL.md": "40a6e5c7114ea565a2e640663b05fe128ad47c9c1d125211cfc58957b8e84163",
    "omh-github-issue-intake/SKILL.md": "ee5dfe3343d5deafe3aff7f49fcbfcd69feb42aa41bfb8a71501a45a057eedad",
    "omh-harness-session-inventory/SKILL.md": "f76e9eda71d216b5784947e732e1a818daa3af7ab205b2c7a64f3be95b122768",
    "omh-idea-to-deploy/SKILL.md": "005a6c5691a98d9876da7c954b8c060840f1470ad0848bf75ec52d3ffaac6797",
    "omh-idea-to-deploy/references/project-bootstrap.md": "dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7",
    "omh-image-cards/SKILL.md": "47aba256922c5ce822f57cbc63bc184c833bd97718009c626f1db0ab8c2e669c",
    "omh-inference-serving/SKILL.md": "d357a82bf576620aac11270f65caea1f232bdb9c15515f52f31630854007aa63",
    "omh-inference-serving/references/serving-bench.md": "31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0",
    "omh-inference-serving/references/serving-runbooks.md": "da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e",
    "omh-instinct-ledger/SKILL.md": "db74247a2a84274de14feeb7097b75c5061a3565ccc37a4de42245c15177ea64",
    "omh-jit-learn/SKILL.md": "cc30647c56414741ee70528c2ea3300f5115d3009f7f0ff833d6737845b2bdb4",
    "omh-legal-compliance-review/SKILL.md": "20c1242de604e9fcb01727b400efa5daf128a70dc133210c8aa37af9d2297509",
    "omh-legal-compliance-review/references/negotiation-preparation.md": "a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1",
    "omh-legal-compliance-review/references/procedure.md": "670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58",
    "omh-lifecycle-growth/SKILL.md": "e19e3cb197142fc4a41f658ac301547d529eb54698ac1d7a07a06ab439fe14d6",
    "omh-lifecycle-growth/references/procedure.md": "7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de",
    "omh-live-incident-response/SKILL.md": "96542b38eba9dba656569cefd1f4109d51efd8d29a8e0e2bd9888ff94a576030",
    "omh-live-incident-response/references/incident-command-method.md": "8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7",
    "omh-live-info/SKILL.md": "273149a89d360c7f05f6d4b9fd16391d2e337355130d41142ae18d0dc06520e0",
    "omh-llm-app-dev/SKILL.md": "af9664d1ad110e70fbeb85ac4b671a7f1b9db2a80dce0037e9731118f9db65a1",
    "omh-llm-app-dev/references/build-rails.md": "35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149",
    "omh-llm-app-dev/references/eval-harness.md": "959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd",
    "omh-llm-app-dev/references/public-board.md": "e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca",
    "omh-llm-app-dev/references/stateful-contracts.md": "7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816",
    "omh-localization-review/SKILL.md": "045d53ee5c967b73a046214497d562124d55ab3dd85b4f15ed2fc19bae0acc00",
    "omh-materials-package/SKILL.md": "b899c87d480f65f0256892a237be627239aa17e7fc7d48506ab756f3af3b1dea",
    "omh-media-input/SKILL.md": "1561b2e4a0f463e3df42b44cdffc75f287a0d072d8b14b0c2119c03a60689b3a",
    "omh-meeting-brief/SKILL.md": "a0d9368ad65e0b4e4f5a88eb19e7006b57b31a5b792e29153c2d9c14d4554cb8",
    "omh-memory-new/SKILL.md": "4b055fc91ae8c729ec1190c8ba7a4c9baaba04c12dfb524df1781d25fc818c3f",
    "omh-native-debugging/SKILL.md": "3c4e71bc5956eb9c0bc4c16efe8de1da624e7ce44bf2ed05fec73e2f9ae80ffa",
    "omh-native-debugging/references/native-debug-loop.md": "3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d",
    "omh-operating-rhythm/SKILL.md": "709ea7a6884876085ddd311d90b35bf8c4a5fcc402c16be42252264b1635be26",
    "omh-ops-observability-card/SKILL.md": "a0f56e0eb499d60db06aea84e90d1e015af188ed3c141c4dad7e35a5dfc5b714",
    "omh-ops-review/SKILL.md": "f960b22abb3ba333185522d51784bee0b422e7c71a2b8db037a24c96860632f6",
    "omh-paper-learning/SKILL.md": "248c2883d8f1b0e89f71171eb03a1320ec9ae13b8bcca8e81967bca30cc39c48",
    "omh-people-ops/SKILL.md": "59fd3e99633ac4bc24d684a2f2716eb4b8ec812f684ac84f3661b6756b175dbb",
    "omh-physical-device-readiness/SKILL.md": "8f7e007abb95f11b89d28ccb9d411fa1cb1ae622fa53a80616ec62e061347e75",
    "omh-plan/SKILL.md": "0f18e6cf54a5702c29f9c861f8ff1dcc72122509cabe1c31dff47ac3c310c88f",
    "omh-plan/references/project-constitution.md": "577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da",
    "omh-product-brief/SKILL.md": "1a72eb4128ce3f927b52f9e021058cf21a251a9d9bf4ea76046000b7795d3872",
    "omh-product-discovery-validation/SKILL.md": "62538e5fdc785e4cb548a095fdc503da733b76786bc36659097c4229aec9e183",
    "omh-product-discovery-validation/references/procedure.md": "c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a",
    "omh-production-audit/SKILL.md": "ec5da405340df1a55a9ad7a7a204166531651c37787d5cb6ce22d78de92c801a",
    "omh-provider-profile-posture/SKILL.md": "86f5720e1d6fe0220d50cee42dc1ae75ee43061270523872992a5833eab6ad9a",
    "omh-refactor-plan/SKILL.md": "2488255f6aa62165715be681236798606b9992e8a3142ad2bbc3f4d750a9bc99",
    "omh-refactor-plan/references/dependency-upgrade.md": "b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0",
    "omh-refactor-plan/references/refactor-phases.md": "492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035",
    "omh-reliability-review/SKILL.md": "dfdefd90bd970f3d40612608c15b2c1348f06e91139df4e42c473405361beb37",
    "omh-report-package/SKILL.md": "b5ecc307c054283b5d552f6345645a41c318d9c81cf5e1cb9ea2746348ad283c",
    "omh-research-brief/SKILL.md": "d7b385f0f73fe20ee5fda984acde6229b9a663486608991eb1f097a001146392",
    "omh-rules-distill/SKILL.md": "5bea104f358c4c851fa23fe58904a7e7c63c4d4f360c056023675421dfd54947",
    "omh-run-efficiency/SKILL.md": "5c48f659139e97a8cca57e51fb93a4fe006682689a21cdfa73907e49dd756d44",
    "omh-running-work-board/SKILL.md": "4056366ffd30adee8136e2282ae2bc975a3ac0c0074b80756ea09f6dcbd496ed",
    "omh-rust/SKILL.md": "7c658499bafd1de3c54e2f35be322dfe246ea5efecd9627037ea2ca422cdb9f4",
    "omh-rust/references/rust-discipline.md": "7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844",
    "omh-rust/references/ub-escalation.md": "b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768",
    "omh-sales-development/SKILL.md": "f2ac90ea45684809641ffd7c49b06df5aedc98009babe6470441ba350ab21c15",
    "omh-sales-development/references/procedure.md": "0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70",
    "omh-sales-pipeline-review/SKILL.md": "e32cd4a816e7c5a88567ba80df8573be6c4696379be273fbf59336c6680a6b3d",
    "omh-sales-pipeline-review/references/procedure.md": "ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138",
    "omh-security-safety-review/SKILL.md": "34856dee03f4b3c0215e44e51d15a042cb441c0a58782e6b24e1c4a7edb87d6c",
    "omh-security-safety-review/references/credential-rotation.md": "2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065",
    "omh-skill-health/SKILL.md": "9ea843bc1035bffff5fd6eaac63a6f97f8ca5db4253d4d39b90d419a282c1ebc",
    "omh-skill-scout/SKILL.md": "83c6fe30254885510c002277e2aada3864739dc514b8b652993150a4f91f26fc",
    "omh-source-finder/SKILL.md": "3fdf0070dd65440488eeeb6d04dc6e98a0021f4e7214d6bd385bef9befeb6526",
    "omh-support-operations/SKILL.md": "7773a91fb7258c7f80280266194b6df244492a01585ed150c518714457e0f8c1",
    "omh-tech-debt-audit/SKILL.md": "b080b6fb79f99a796ff4830641b5509ad464b6d6bd38fdad169b1d418fe59f9e",
    "omh-tech-debt-audit/references/debt-dimensions.md": "7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75",
    "omh-terminal/SKILL.md": "2e195d330ee4284276d8a486891bfaef4626e155130f592d24086b054e768f5f",
    "omh-toolbelt-readiness/SKILL.md": "16982df8ecba2fb01c9afea2e540c8b174e4b67740d028287ff8b38ed7b1c43b",
    "omh-verification-gate/SKILL.md": "2e53924ae2593aa5a9de7f8280cd993cba595ad4dacddb9fcfacd0eae69867d0",
    "omh-verification-gate/references/generated-artifact-provenance.md": "91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad",
    "omh-verification-gate/references/requirement-coverage-map.md": "91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19",
    "omh-visual-qa/SKILL.md": "2b27edb565e5f37bb69e7d45bea2df50a499c72a57945ce27562a27122f52c41",
    "omh-visual-qa/references/visual-verdict-contract.md": "7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759",
    "omh-voice-input/SKILL.md": "c1c6124525be0a3c95cbf8106088c6a157e8eef6fa4728b9a4ba0b91d71b6b57",
    "omh-web-research/SKILL.md": "bbddec7336589a938f71691b88fcde358fc65467efeeb7731b8cf2927a4afa5c",
    "omh-wiki/SKILL.md": "334f1d7edebb4e63134f0938d66dcbb93098902b7d6e8b55b156718fca4b5547",
    "omh-wiki/references/wiki-blueprint.md": "6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c",
    "omh-wiki/references/wiki-operations.md": "656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528",
    "omh-wiki/references/wiki-patterns.md": "f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e",
    "omh-workspace-audit/SKILL.md": "2499a100737a79d5d775e38a983971c2ac22fac2d0386de61b65aafcca840fe7",
    "ulw-context/SKILL.md": "7ba238fbd1e2752badc98d36380a4ce2c5701e77f3eba7cf98100fce4a366010",
    "ulw-context/references/decision-frontier.md": "122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df",
    "ulw-context/references/project-terms.md": "0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45",
    "ulw-interview/SKILL.md": "553e8f190d148bdb870ae5d0a82276b4dcdab1862a9b7ff0812f909bd8458d15",
    "ulw-interview/references/ambiguity-taxonomy.md": "af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a",
    "ulw-loop/SKILL.md": "624963ae486aab64f56d0f0781051184a6863a9e1dea898b4a85f0168c02efe9",
    "ulw-loop/references/goal-constraint-discipline.md": "e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f",
    "ulw-loop/references/measured-loop-discipline.md": "1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb",
    "ulw-perf/SKILL.md": "1ae9136c6abef70c11048a5b07ede1d0d10439248058a23237cf32cf8d28964f",
    "ulw-plan/SKILL.md": "ccb3d8edce24e74c1a872c3108ad3f3b52c7466b17d705aa97ac0cf2be841a0d",
    "ulw-qa/SKILL.md": "1a384bbfcfbb710c7b82e516e4cc98faac6827dd0ce771fe2a01e82da980bd8d",
    "ulw-research/SKILL.md": "b96f347662adbdadc2ab6e8a3b1f7935a879acee98eb5d093dc7f343294b8b80",
    "ulw-research/references/briefing-format.md": "466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac",
    "ulw-work/SKILL.md": "104021f9f990e8b0b4940f71b295bfcbc57afc5e2c34e37cd46791e06ffc07e9",
    "ulw-work/references/dependency-topology.md": "b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac"
  },
  "schema_version": "omh_agent_skills_projection/v1",
  "target_dirs": [
    "."
  ]
}
OMH_RECEIPT
printf 'Installed cursor skills in %s\n' "$target"
cat <<'OMH_SKILLS'
omh-accessibility-audit
omh-adversarial-consensus
omh-agent-debug
omh-agent-ops-review
omh-ai-slop-cleaner
omh-apple-design
omh-application-threat-model
omh-apps
omh-ask
omh-award-bar-score
omh-backend
omh-build-failure-triage
omh-cancel
omh-code-review
omh-codebase-onboarding
omh-codebase-uml
omh-codegraph-refresh
omh-content-operator
omh-context-budget-review
omh-cto-loop
omh-curriculum-design
omh-data-analysis
omh-decide
omh-decision-prototype
omh-decision-recall
omh-deliverable-package
omh-deploy-and-monitor
omh-design-orchestration
omh-design-quality-gate
omh-docs
omh-external-connector-readiness
omh-failure-signal-audit
omh-feedback-triage
omh-files
omh-finance-analysis
omh-frontend
omh-frontend-refactor
omh-github-event-ops
omh-github-issue-intake
omh-harness-session-inventory
omh-idea-to-deploy
omh-image-cards
omh-inference-serving
omh-instinct-ledger
omh-jit-learn
omh-legal-compliance-review
omh-lifecycle-growth
omh-live-incident-response
omh-live-info
omh-llm-app-dev
omh-localization-review
omh-materials-package
omh-media-input
omh-meeting-brief
omh-memory-new
omh-native-debugging
omh-operating-rhythm
omh-ops-observability-card
omh-ops-review
omh-paper-learning
omh-people-ops
omh-physical-device-readiness
omh-plan
omh-product-brief
omh-product-discovery-validation
omh-production-audit
omh-provider-profile-posture
omh-refactor-plan
omh-reliability-review
omh-report-package
omh-research-brief
omh-rules-distill
omh-run-efficiency
omh-running-work-board
omh-rust
omh-sales-development
omh-sales-pipeline-review
omh-security-safety-review
omh-skill-health
omh-skill-scout
omh-source-finder
omh-support-operations
omh-tech-debt-audit
omh-terminal
omh-toolbelt-readiness
omh-verification-gate
omh-visual-qa
omh-voice-input
omh-web-research
omh-wiki
omh-workspace-audit
ulw-context
ulw-interview
ulw-loop
ulw-perf
ulw-plan
ulw-qa
ulw-research
ulw-work
OMH_SKILLS
