FROM runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel-ubuntu22.04

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y ffmpeg curl && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install runpod

# Copy app files
COPY . .

# Set environment variable (You will pass HF_TOKEN from RunPod UI)
ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "runpod_handler.py"]